### ISSUE TITLE
transcr.: Word separation / pb

### ISSUE THREAD

**Issue by BOberreither** [karl-kraus/wpn-static#79]
On page 39, there is a word separation at the end of the page, but the separation-minus is displayed on the following page in an extra line.

**Comment by linxOD** [comment]
this is because the word-break information is in the `lb break="no"` element. Which is only available on the next page. Maybe you can extra information that this is a word and pagebreak at the same time?

**Comment by BOberreither** [comment]
In the last lb of page 39 or in the first lb of page 40?

**Comment by linxOD** [comment]
For both pages. Since it is necessary to split the main file into a file for each page, the file for page 39 will have no information on the wordbreak. It would require some sort of placeholder element after "...die Anbringung von Wahl".
On page 40 the `lb break="no"` element is the first lb element which should anyway receive a `n="first"` Attribute to indicate that it does not require rendering. This would be enough to remove the extra "-".

**Comment by linxOD** [comment]
same issue for pages 193 and 194

**Comment by BOberreither** [comment]
@linxOD Hm, I can add the lb n=last and first, no problem, but an extra element at the end of the line when it's the last line and there is a word break, I don't think that's still TEI ... I'll think about it/ask around.

**Comment by BOberreither** [comment]
@linxOD I did a first push with `lb n=first` for the first line in every page; first lines of paragraphs, quotes etc. will be marked soon.
Also, I added lb n="firstLast" where the line is the first and at the same time the only line of the page / the paragraph (not yet complete)

**Comment by linxOD** [comment]
requires testing
